apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-deployment
  namespace: temp-validation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert
  template:
    metadata:
      labels:
        app: alert      
    spec:
      containers:
      - name: alert
        image: alert:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: ingestor-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password