apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator-deployment
  namespace: temp-validation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
    spec:
      containers:
      - name: simulator
        image: simulator:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: ingestor-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password