name: Dev Auto Deploy

on:
  push:
    branches:
      - dev

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy-to-dev-server:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync and Rebuild Containers
        run: |
          rsync -avz --delete --exclude 'pgdata/' ./ ${{ secrets.DEV_USER }}@${{ secrets.DEV_IP }}:/opt/temp-validation/
          ssh ${{ secrets.DEV_USER }}@${{ secrets.DEV_IP }} "cd /opt/temp-validation && docker compose down && docker compose up -d --build"
